name: flutterotica
description: "Literotica App in Flutter"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  loggy: ^2.0.3
  flutter_loggy: any
  infinite_scroll_pagination: ^4.0.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.2
  multi_dropdown: ^2.1.2
  sembast: ^3.5.0+1
  path_provider: ^2.1.1
  dio: ^5.4.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  persistent_bottom_nav_bar_v2: ^5.2.3
  ionicons: ^0.2.2
  flutter_linkify: ^6.0.0
  overlay_support: ^2.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_speed_dial: ^7.0.0
  get_it: ^8.0.0
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  flutter_slidable: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/data/
