name: flutterotica
description: "Literotica App in Flutter"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  loggy: ^2.0.3
  flutter_loggy: any
  infinite_scroll_pagination: ^4.0.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1
  multi_dropdown: ^2.1.2
  sembast: ^3.8.5
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  persistent_bottom_nav_bar_v2: ^5.4.0
  ionicons: ^0.2.2
  flutter_linkify: ^6.0.0
  overlay_support: ^2.1.0
  flutter_html: ^3.0.0
  flutter_speed_dial: ^7.0.0
  get_it: ^8.0.3
  auto_size_text: ^3.0.0
  intl: ^0.20.2
  flutter_slidable: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/data/
